spring.datasource.url=jdbc:mysql://localhost:3306/smartagriculture?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path=/api
server.port=8081

logging.level.com.myself.app=debug
server.servlet.encoding.charset=UTF-8

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=balejizaineb@gmail.com
spring.mail.password=uqycewnjstwkwwbl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.security.oauth2.client.registration.google.client-id=741527238279-i4od5t8bheplggi4ljus1rcplh0lvn4c.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email